<?php
/** @var \Commerce365\Invoices\Block\InvoiceList $block */
$totalResults = 0;
$invoices = [];

$invoicesResponse = $this->getInvoices();
if (!empty($invoicesResponse)) {
    $invoices = $invoicesResponse["salesDocuments"];
    $totalResults = $invoicesResponse["totalResults"];
}
?>

<div class="table-wrapper orders-history">
<?php if (count($invoices) > 0): ?>
    <form action="<?= $this->getFilterActionUrl() ?>" method="get">
        <div class="search-form-fields">
            <input type="text" placeholder="<?= __('Search...') ?>" name="searchString"/>
            <button type="submit" title="<?= __('Search') ?>" class="action primary">
                <span><?= __('Search') ?></span>
            </button>
        </div>
    </form>
    <?php if ($this->getSearchString()): ?>
        <div>
            <?= __('Current filter')?>: <?= $this->getSearchString()?>
            <a href="<?= $this->getFilterActionUrl()?>"><?= __('Reset') ?></a>
        </div>
    <?php endif; ?>
    <table class="data table table-order-items history" id="my-orders-table">
        <thead>
        <tr>
            <th scope="col" class="col id">
                <a href="<?= $this->getSortLink('No.')?>">
                    <?php echo __('Invoice #') ?>
                    <?= $this->getSortIcon('No.') ?>
                </a>
            </th>
            <th scope="col" class="col date">
                <a href="<?= $this->getSortLink('Document Date')?>">
                    <?php echo __('Date') ?>
                    <?= $this->getSortIcon('Document Date') ?>
                </a>
            </th>
            <th scope="col" class="col status">
                <a href="<?= $this->getSortLink('Order No.')?>">
                    <?php echo __('From Order #') ?>
                    <?= $this->getSortIcon('Order No.') ?>
                </a>
            </th>
            <th scope="col" class="col shipping">
                <a href="<?= $this->getSortLink('Ship-to Name')?>">
                    <?php echo __('Bill To') ?>
                    <?= $this->getSortIcon('Ship-to Name') ?>
                </a>
            </th>
            <th scope="col" class="col total">
                <a href="<?= $this->getSortLink('Amount Including VAT')?>">
                    <?php echo __('Invoice Total') ?>
                    <?= $this->getSortIcon('Amount Including VAT') ?>
                </a>
            </th>
            <th scope="col" class="col total">
                <a href="<?= $this->getSortLink('Remaining Amount')?>">
                    <?php echo __('Open Amount') ?>
                    <?= $this->getSortIcon('Remaining Amount') ?>
                </a>
            </th>
            <th scope="col" class="col actions">&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($invoices as $invoice): ?>
            <tr>
                <td data-th="Order #" class="col id"><?= $invoice["No."] ?></td>
                <td data-th="Date" class="col date"><?= date_format(date_create($invoice["Document Date"]), "d-m-Y") ?></td>
                <td data-th="Status #" class="col id"><?= $invoice["Order No."] ?></td>
                <td data-th="Ship To #" class="col id"><?= $invoice["Ship-to Name"] ?></td>
                <td data-th="Total" class="col total"><?= $invoice["Currency Code"] ?> <?= number_format((float)$invoice["Amount Including VAT"], 2, ',', '.') ?></td>
                <td data-th="Total" class="col total"><?= $invoice["Currency Code"] ?> <?= number_format((float)$invoice["Remaining Amount"], 2, ',', '.') ?></td>
                <td data-th="Actions" class="col actions">
                    <a href="<?= $this->getViewUrl($invoice["id"]) ?>" class="action view">
                        <span><?=__("View Invoice") ?></span>
                    </a>
                    <a href="<?= $invoice["PDFUrl"] ?>" class="action order" target="_blank">
                        <span>PDF</span>
                    </a>
                </td>
             </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <div class="message info empty"><span><?php echo __('No invoices found.') ?></span></div>
<?php endif; ?>
</div>

<?php if ($totalResults > $block->getPageSize()): ?>
    <div>
        <?php echo __('Page:') ?> <?php echo $block->getPage() ?> <?php echo __('of') ?> <?php echo $invoicesResponse["totalPages"] ?>
    </div>
    <div>
        <?php if ($block->getPage() > 1): ?>
        <a href="<?= $this->getPreviousPageUrl() ?>" class="action order"><?php echo __('Previous') ?></a>
        <?php endif; ?>
        <?php if ($block->getPage() > 1 && $block->getPage() < $invoicesResponse["totalPages"]): ?>
            -
        <?php endif; ?>
        <?php if ($block->getPage() < $invoicesResponse["totalPages"]): ?>
        <a href="<?= $this->getNextPageUrl($block->getPage()) ?>" class="action order"><?php echo __('Next') ?></a>
        <?php endif; ?>
    </div>
<?php endif; ?>

<!--

Below is a list of all sales invoice header fields
All these fields are available in the API response, as well as any custom field added by customer/partner/other ISV

"id": "CD9F76C2-7C06-EB11-81A2-E016CCC29A3B",
"Sell-to Customer No.": "C00010",
"No.": "103223",
"Bill-to Customer No.": "C00010",
"Bill-to Name": "Signify HQ",
"Bill-to Name 2": "",
"Bill-to Address": "High Tech Campus 48",
"Bill-to Address 2": "",
"Bill-to City": "Eindhoven",
"Bill-to Contact": "Frits Philips",
"Your Reference": "",
"Ship-to Code": "",
"Ship-to Name": "Signify HQ",
"Ship-to Name 2": "",
"Ship-to Address": "High Tech Campus 48",
"Ship-to Address 2": "",
"Ship-to City": "Eindhoven",
"Ship-to Contact": "Frits Philips",
"Order Date": "2020-08-10",
"Posting Date": "2020-08-10",
"Shipment Date": "2020-08-10",
"Posting Description": "Order 101018",
"Payment Terms Code": "14 DAYS",
"Due Date": "2020-08-24",
"Payment Discount %": 0,
"Pmt. Discount Date": "2020-08-10",
"Shipment Method Code": "CFR",
"Location Code": "MAIN",
"Shortcut Dimension 1 Code": "",
"Shortcut Dimension 2 Code": "",
"Customer Posting Group": "EU",
"Currency Code": "EUR",
"Currency Factor": 1.548467017652524,
"Customer Price Group": "",
"Prices Including VAT": false,
"Invoice Disc. Code": "C00010",
"Customer Disc. Group": "",
"Language Code": "",
"Salesperson Code": "",
"Order No.": "101018",
"Comment": false,
"No. Printed": 0,
"On Hold": "",
"Applies-to Doc. Type": 0,
"Applies-to Doc. No.": "",
"Bal. Account No.": "",
"Amount": 1002.48,
"Amount Including VAT": 1002.48,
"VAT Registration No.": "",
"Reason Code": "",
"Gen. Bus. Posting Group": "EU",
"EU 3-Party Trade": false,
"Transaction Type": "",
"Transport Method": "",
"VAT Country/Region Code": "NL",
"Sell-to Customer Name": "Signify HQ",
"Sell-to Customer Name 2": "",
"Sell-to Address": "High Tech Campus 48",
"Sell-to Address 2": "",
"Sell-to City": "Eindhoven",
"Sell-to Contact": "Frits Philips",
"Bill-to Post Code": "5656 AE",
"Bill-to County": "",
"Bill-to Country/Region Code": "NL",
"Sell-to Post Code": "5656 AE",
"Sell-to County": "",
"Sell-to Country/Region Code": "NL",
"Ship-to Post Code": "5656 AE",
"Ship-to County": "",
"Ship-to Country/Region Code": "NL",
"Bal. Account Type": 0,
"Exit Point": "",
"Correction": false,
"Document Date": "2020-08-10",
"External Document No.": "",
"Area": "",
"Transaction Specification": "",
"Payment Method Code": "BANK",
"Shipping Agent Code": "DHL",
"Package Tracking No.": "",
"Pre-Assigned No. Series": "",
"No. Series": "S-INV+",
"Order No. Series": "S-ORD",
"Pre-Assigned No.": "",
"User ID": "USER",
"Source Code": "SALES",
"Tax Area Code": "",
"Tax Liable": false,
"VAT Bus. Posting Group": "EU",
"VAT Base Discount %": 0,
"Invoice Discount Calculation": 0,
"Invoice Discount Value": 0,
"Prepayment No. Series": "",
"Prepayment Invoice": false,
"Prepayment Order No.": "",
"Quote No.": "",
"Last Email Sent Time": "0001-01-01T00:00:00",
"Last Email Sent Status": 0,
"Sent as Email": false,
"Last Email Notif Cleared": false,
"Sell-to Phone No.": "+31 (0) 40 275 0000",
"Sell-to E-Mail": "frits@signify.com",
"Payment Instructions Name": "Check payment",
"Payment Reference": "",
"Dimension Set ID": 0,
"Payment Service Set ID": 0,
"Document Exchange Identifier": "",
"Document Exchange Status": 0,
"Doc. Exch. Original Identifier": "",
"Coupled to CRM": false,
"Direct Debit Mandate ID": "",
"Closed": false,
"Remaining Amount": 1002.48,
"Cust. Ledger Entry No.": 3376,
"Invoice Discount Amount": 0,
"Cancelled": false,
"Corrective": false,
"Reversed": false,
"Campaign No.": "",
"Sell-to Contact No.": "CT000024",
"Bill-to Contact No.": "CT000024",
"Opportunity No.": "",
"Responsibility Center": "",
"Price Calculation Method": 1,
"Allow Line Disc.": true,
"Get Shipment Used": false,
"NC365 Staging Order No.": "",
"NC365 Store Code": "",

"Lines": [],
"PDFUrl": "https://commerce365.blob.core.windows.net/123456879/Invoice_103223_76BDF924-3ED4-45E5-B556-304C6C138B55.pdf",
"TableNo": 112,
"CustomerId": 6

-->

<!--

Below is a list of all sales invoice line fields

"Sell-to Customer No.": "C00010",
"Document No.": "103223",
"Line No.": 10000,
"Type": 2,
"No.": "1896-S",
"Location Code": "MAIN",
"Posting Group": "RESALE",
"Shipment Date": "2020-08-15",
"Description": "ATHENS Desk",
"Description 2": "",
"Unit of Measure": "Piece",
"Quantity": 1,
"Unit Price": 1002.478,
"Unit Cost (LCY)": 506.6,
"VAT %": 0,
"Line Discount %": 0,
"Line Discount Amount": 0,
"Amount": 1002.48,
"Amount Including VAT": 1002.48,
"Allow Invoice Disc.": true,
"Gross Weight": 39.79,
"Net Weight": 34.6,
"Units per Parcel": 0,
"Unit Volume": 1.2,
"Appl.-to Item Entry": 0,
"Shortcut Dimension 1 Code": "",
"Shortcut Dimension 2 Code": "",
"Customer Price Group": "",
"Job No.": "",
"Work Type Code": "",
"Shipment No.": "",
"Shipment Line No.": 0,
"Order No.": "101018",
"Order Line No.": 10000,
"Bill-to Customer No.": "C00010",
"Inv. Discount Amount": 0,
"Drop Shipment": false,
"Gen. Bus. Posting Group": "EU",
"Gen. Prod. Posting Group": "RETAIL",
"VAT Calculation Type": 1,
"Transaction Type": "",
"Transport Method": "",
"Attached to Line No.": 0,
"Exit Point": "",
"Area": "",
"Transaction Specification": "",
"Tax Category": "",
"Tax Area Code": "",
"Tax Liable": false,
"Tax Group Code": "",
"VAT Clause Code": "",
"VAT Bus. Posting Group": "EU",
"VAT Prod. Posting Group": "STANDARD",
"Blanket Order No.": "",
"Blanket Order Line No.": 0,
"VAT Base Amount": 1002.48,
"Unit Cost": 784.453,
"System-Created Entry": false,
"Line Amount": 1002.48,
"VAT Difference": 0,
"VAT Identifier": "STANDARD",
"IC Partner Ref. Type": 0,
"IC Partner Reference": "",
"Prepayment Line": false,
"IC Partner Code": "",
"Posting Date": "2020-08-10",
"Pmt. Discount Amount": 0,
"Line Discount Calculation": 0,
"Dimension Set ID": 0,
"Job Task No.": "",
"Job Contract Entry No.": 0,
"Deferral Code": "",
"Variant Code": "",
"Bin Code": "",
"Qty. per Unit of Measure": 1,
"Unit of Measure Code": "PCS",
"Quantity (Base)": 1,
"FA Posting Date": "0001-01-01",
"Depreciation Book Code": "",
"Depr. until FA Posting Date": false,
"Duplicate in Depreciation Book": "",
"Use Duplication List": false,
"Responsibility Center": "",
"Cross-Reference No.": "",
"Unit of Measure (Cross Ref.)": "",
"Cross-Reference Type": 0,
"Cross-Reference Type No.": "",
"Item Category Code": "TABLE",
"Nonstock": false,
"Purchasing Code": "",
"Appl.-from Item Entry": 0,
"Return Reason Code": "",
"Price Calculation Method": 1,
"Allow Line Disc.": true,
"Customer Disc. Group": "",
"Price description": ""

-->
