<?php
/** @var \Commerce365\Invoices\Block\InvoiceList $block */
$totalResults = 0;
$invoices = [];

$invoicesResponse = $this->getInvoices();
if (!empty($invoicesResponse)) {
    $invoices = $invoicesResponse["salesDocuments"];
    $totalResults = $invoicesResponse["totalResults"];
}
?>

<div class="table-wrapper orders-history">
<?php if (count($invoices) > 0): ?>
    <form action="<?= $this->getFilterActionUrl() ?>" method="get">
        <div class="search-form-fields">
            <input type="text" placeholder="<?= __('Search...') ?>" name="searchString"/>
            <button type="submit" title="<?= __('Search') ?>" class="action primary">
                <span><?= __('Search') ?></span>
            </button>
        </div>
    </form>
    <?php if ($this->getSearchString()): ?>
        <div>
            <?= __('Current filter')?>: <?= $this->getSearchString()?>
            <a href="<?= $this->getFilterActionUrl()?>"><?= __('Reset') ?></a>
        </div>
    <?php endif; ?>
    <table class="data table table-order-items history" id="my-orders-table">
        <thead>
        <tr>
            <?php if($this->isColumnExists($invoices, 'No.')): ?>
            <th scope="col" class="col id">
                <a href="<?= $this->getSortLink('No.')?>">
                    <?= __('Invoice #') ?>
                    <?= $this->getSortIcon('No.') ?>
                </a>
            </th>
            <?php endif; ?>
            <?php if($this->isColumnExists($invoices, 'Document Date')): ?>
            <th scope="col" class="col date">
                <a href="<?= $this->getSortLink('Document Date')?>">
                    <?= __('Date') ?>
                    <?= $this->getSortIcon('Document Date') ?>
                </a>
            </th>
            <?php endif; ?>
            <?php if($this->isColumnExists($invoices, 'Order No.')): ?>
            <th scope="col" class="col status">
                <a href="<?= $this->getSortLink('Order No.')?>">
                    <?= __('From Order #') ?>
                    <?= $this->getSortIcon('Order No.') ?>
                </a>
            </th>
            <?php endif; ?>
            <?php if($this->isColumnExists($invoices, 'Ship-to Name')): ?>
            <th scope="col" class="col shipping">
                <a href="<?= $this->getSortLink('Ship-to Name')?>">
                    <?= __('Bill To') ?>
                    <?= $this->getSortIcon('Ship-to Name') ?>
                </a>
            </th>
            <?php endif; ?>
            <?php if($this->isColumnExists($invoices, 'Amount Including VAT')): ?>
            <th scope="col" class="col total">
                <a href="<?= $this->getSortLink('Amount Including VAT')?>">
                    <?= __('Invoice Total') ?>
                    <?= $this->getSortIcon('Amount Including VAT') ?>
                </a>
            </th>
            <?php endif; ?>
            <?php if($this->isColumnExists($invoices, 'Remaining Amount')): ?>
            <th scope="col" class="col total">
                <a href="<?= $this->getSortLink('Remaining Amount')?>">
                    <?= __('Open Amount') ?>
                    <?= $this->getSortIcon('Remaining Amount') ?>
                </a>
            </th>
            <?php endif; ?>
            <th scope="col" class="col actions">&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($invoices as $invoice): ?>
            <tr>
                <?php if($this->isColumnExists($invoices, 'No.')): ?>
                    <td data-th="Order #" class="col id"><?= $invoice["No."] ?></td>
                <?php endif; ?>
                <?php if($this->isColumnExists($invoices, 'Document Date')): ?>
                    <td data-th="Date" class="col date"><?= date_format(date_create($invoice["Document Date"]), "d-m-Y") ?></td>
                <?php endif; ?>
                <?php if($this->isColumnExists($invoices, 'Order No.')): ?>
                    <td data-th="Status #" class="col id"><?= $invoice["Order No."] ?></td>
                <?php endif; ?>
                <?php if($this->isColumnExists($invoices, 'Ship-to Name')): ?>
                    <td data-th="Ship To #" class="col id"><?= $invoice["Ship-to Name"] ?></td>
                <?php endif; ?>
                <?php if($this->isColumnExists($invoices, 'Amount Including VAT')): ?>
                    <td data-th="Total" class="col total"><?= $invoice["Currency Code"] ?> <?= number_format((float)$invoice["Amount Including VAT"], 2, ',', '.') ?></td>
                <?php endif; ?>
                <?php if($this->isColumnExists($invoices, 'Remaining Amount')): ?>
                    <td data-th="Total" class="col total"><?= $invoice["Currency Code"] ?> <?= number_format((float)$invoice["Remaining Amount"], 2, ',', '.') ?></td>
                <?php endif; ?>
                <td data-th="Actions" class="col actions">
                    <a href="<?= $this->getViewUrl($invoice["id"]) ?>" class="action view">
                        <span><?=__("View Invoice") ?></span>
                    </a>
                    <a href="<?= $invoice["PDFUrl"] ?>" class="action order" target="_blank">
                        <span>PDF</span>
                    </a>
                </td>
             </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <div class="message info empty"><span><?= __('No invoices found.') ?></span></div>
<?php endif; ?>
</div>

<?php if ($totalResults > $block->getPageSize()): ?>
    <div>
        <?= __('Page:') ?> <?= $block->getPage() ?> <?= __('of') ?> <?= $invoicesResponse["totalPages"] ?>
    </div>
    <div>
        <?php if ($block->getPage() > 1): ?>
        <a href="<?= $block->getPreviousPageUrl() ?>" class="action order"><?= __('Previous') ?></a>
        <?php endif; ?>
        <?php if ($block->getPage() > 1 && $block->getPage() < $invoicesResponse["totalPages"]): ?>
            -
        <?php endif; ?>
        <?php if ($block->getPage() < $invoicesResponse["totalPages"]): ?>
        <a href="<?= $block->getNextPageUrl() ?>" class="action order"><?= __('Next') ?></a>
        <?php endif; ?>
    </div>
<?php endif; ?>
