<?php
/** @var \Commerce365\Invoices\Block\InvoiceDetails  $block */
$invoice = $block->getInvoice();
$invoiceLines = $block->safeGet($invoice, "Lines", []);
$status = 'Paid';
$remainingAmount = (float) $block->safeGet($invoice, "Remaining Amount", 0);

if ($remainingAmount > 0) {
    $status = __('Unpaid') . ' (' . __('remaining') . ': &euro; ' . number_format($remainingAmount, 2, ',', '.') . ')';
}
?>

<div class="page-title-wrapper">
    <h1 class="page-title">
        <span class="base" data-ui-id="page-title-wrapper"><?= __('Invoice #') ?> <?= $block->safeGet($invoice, "No."); ?> </span>
    </h1>
    <span class="order-status"><?= $status ?></span>
    <div class="order-date">
        <span class="label"><?= __('Invoice Date:') ?></span> <date><?= date_format(date_create($block->safeGet($invoice, "Document Date")), "d-m-Y") ?></date>
    </div>
</div>

<div class="actions-toolbar order-actions-toolbar">
    <div class="actions">
        <a href="<?= $block->safeGet($invoice, "PDFUrl") ?>" class="action order" target="_blank">
            <span><?= __('Download PDF') ?></span>
        </a>
    </div>
</div>

<ul class="items order-links"><li class="nav item current"><strong><?= __('Items Invoiced') ?></strong></li></ul><div class="order-details-items ordered">

    <div class="order-title">
        <strong><?= __('Items Invoiced') ?></strong>
    </div>

    <div class="table-wrapper order-items">
        <table class="data table table-order-items" id="my-orders-table">
            <caption class="table-caption"><?= __('Items Invoiced') ?></caption>
            <thead>
            <tr>
                <th class="col name"><?= __('Product Name') ?></th>
                <th class="col sku"><?= __('SKU') ?></th>
                <th class="col price"><?= __('Price') ?></th>
                <th class="col qty"><?= __('Qty') ?></th>
                <th class="col subtotal"><?= __('Subtotal') ?></th>
            </tr>
            </thead>

            <?php
            foreach ($invoiceLines as $invoiceLine) {
                $itemNo = '';
                if ((int)$block->safeGet($invoiceLine, "Type") === 2) {
                    $itemNo = $block->safeGet($invoiceLine, "No.");
                }

                if ($block->safeGet($invoiceLine, "Type") < 1) {
                    echo '<tbody>
                            <tr id="order-item-row-1">
                                <td class="col name" data-th="Product Name">
                                    <strong class="product name product-item-name">' . $block->safeGet($invoiceLine, "Description") . '</strong>
                                </td>
                                <td class="col sku" data-th="SKU"></td>
                                <td class="col price" data-th="Price">
                                </td>
                                <td class="col qty" data-th="Qty">
                                </td>
                                <td class="col subtotal" data-th="Subtotal">
                                </td>
                            </tr>
                        </tbody>';
                } else {
                    $qty = (float)$block->safeGet($invoiceLine, "Quantity");
                    if ($qty == 0) {
                        $qty = 1;
                    }

                    echo '<tbody>
                            <tr id="order-item-row-1">
                                <td class="col name" data-th="Product Name">
                                    <strong class="product name product-item-name">' . $block->safeGet($invoiceLine, "Description") . '</strong>
                                </td>
                                <td class="col sku" data-th="SKU">' . $itemNo . '</td>
                                <td class="col price" data-th="Price">
                                    <span class="price-excluding-tax" data-label="Excl. Tax">
                                        <span class="cart-price">
                                            <span class="price">' . $block->safeGet($invoice, "Currency Code") . ' ' . number_format((float)$block->safeGet($invoiceLine, "Amount") / $qty, 2, ',', '.') . '</span>
                                        </span>
                                    </span>
                                </td>
                                <td class="col qty" data-th="Qty">
                                    <ul class="items-qty">
                                        <li class="item">
                                            <span class="content">' . $block->safeGet($invoiceLine, "Quantity") . '</span>
                                        </li>
                                    </ul>
                                </td>
                                <td class="col subtotal" data-th="Subtotal">
                                    <span class="price-excluding-tax" data-label="Excl. Tax">
                                        <span class="cart-price">
                                            <span class="price">' . $block->safeGet($invoice, "Currency Code") . ' ' . number_format((float)$block->safeGet($invoiceLine, "Line Amount"), 2, ',', '.') . '</span>
                                        </span>
                                    </span>
                                </td>
                            </tr>
                        </tbody>';
                }
            }
            ?>

            <tfoot>
            <tr class="subtotal">
                <th colspan="4" class="mark" scope="row">
                    <?= __('Subtotal') ?>
                </th>
                <td class="amount" data-th="Subtotal">
                    <span class="price"><?= $block->safeGet($invoice, "Currency Code"); ?> <?= number_format((float)$block->safeGet($invoice, "Amount"), 2, ',', '.') ?></span>
                </td>
            </tr>
            <tr class="shipping">
                <th colspan="4" class="mark" scope="row">
                    <?= __('VAT') ?>
                </th>
                <td class="amount" data-th="VAT &amp; VAT">
                    <span class="price"><?= $block->safeGet($invoice, "Currency Code"); ?> <?= number_format((float)$block->safeGet($invoice, "Amount Including VAT") - (float)$block->safeGet($invoice, "Amount"), 2, ',', '.') ?></span>
                </td>
            </tr>
            <tr class="grand_total">
                <th colspan="4" class="mark" scope="row">
                    <strong><?= __('Grand Total') ?></strong>
                </th>
                <td class="amount" data-th="Grand Total">
                    <strong><span class="price"><?= $block->safeGet($invoice, "Currency Code"); ?> <?= number_format((float)$block->safeGet($invoice, "Amount Including VAT"), 2, ',', '.') ?></span></strong>
                </td>
            </tr>
            </tfoot>
        </table>
    </div>


    <div class="actions-toolbar">
        <div class="secondary">
            <a class="action back" href="/invoices/invoicelist/">
                <span><?= __('Back to My Invoices') ?></span>
            </a>
        </div>
    </div>
</div>
<div class="block block-order-details-view">
    <div class="block-title">
        <strong><?= __('Invoice Information') ?></strong>
    </div>
    <div class="block-content">
        <div class="box box-order-shipping-address">
            <strong class="box-title"><span><?= __('Shipping Address') ?></span></strong>
            <div class="box-content">
                <address><?= $block->safeGet($invoice, "Ship-to Name"); ?><br/>
                    <?= $block->safeGet($invoice, "Ship-to Address"); ?><br />
                    <?= $block->safeGet($invoice, "Ship-to City"); ?>,  <?= $block->safeGet($invoice, "Ship-to Post Code"); ?><br/>
                    <?= $block->safeGet($invoice, "Ship-to Country/Region Code"); ?><br/>
                </address>
            </div>
        </div>
        <div class="box box-order-shipping-method">
            <strong class="box-title">
                <span><?= __('Shipping Method') ?></span>
            </strong>
            <div class="box-content">
                <div><?= $block->safeGet($invoice, "Shipment Method Code"); ?></div>
            </div>
        </div>
        <div class="box box-order-billing-address">
            <strong class="box-title">
                <span><?= __('Billing Address') ?></span>
            </strong>
            <div class="box-content">
                <address><?= $block->safeGet($invoice, "Bill-to Name"); ?><br/>
                    <?= $block->safeGet($invoice, "Bill-to Address"); ?><br />
                    <?= $block->safeGet($invoice, "Bill-to City"); ?>,  <?= $block->safeGet($invoice, "Bill-to Post Code"); ?><br/>
                    <?= $block->safeGet($invoice, "Bill-to Country/Region Code"); ?><br/>
                </address>
            </div>
        </div>
        <div class="box box-order-billing-method">
            <strong class="box-title">
                <span><?= __('Payment Method') ?></span>
            </strong>
            <div class="box-content">
                <dl class="payment-method checkmemo">
                    <?= $block->safeGet($invoice, "Payment Method Code"); ?>
                    <?= $block->safeGet($invoice, "Payment Terms Code"); ?>
                </dl>
            </div>
        </div>
    </div>
</div>
