<?php declare(strict_types=1);

use Commerce365\Invoices\Block\InvoiceDetails;
use Magento\Framework\Escaper;

/** @var InvoiceDetails  $block */
/** @var Escaper $escaper */

$invoice = $block->getInvoice();
$invoiceLines = $invoice["Lines"];
$status = 'Paid';

if ((float)$invoice["Remaining Amount"] > 0) {
    $status = __('Unpaid') . ' (' . __('remaining') . ': &euro; ' . number_format((float)
    $invoice["Remaining Amount"], 2, ',', '.') . ')';
}
?>

<div class="md:flex md:justify-between items-center mb-3">
    <div class="lg:flex items-center text-center md:text-left">
        <div class="lg:inline-block">
            <h2 class="text-2xl">
                <span><?= $escaper->escapeHtml(__('Invoice # %1', $invoice["No."])) ?></span>
            </h2>
            <div class="order-date">
                <span><?= $escaper->escapeHtml(__('Invoice Date:')) ?></span>
                <date><?= date_format(date_create($invoice["Document Date"]), "d-m-Y") ?></date>
            </div>
        </div>
        <div class="mt-3 md:mt-0 lg:inline-block lg:ml-5">
            <span class="order-status inline-block px-3 py-3 border rounded border-container">
                <?= $escaper->escapeHtml($status) ?>
            </span>
        </div>
    </div>
    <a href="<?= $escaper-> escapeUrl($invoice["PDFUrl"]) ?>" class="btn btn-secondary order" target="_blank"
        rel="noopener noreferrer">
        <span><?= $escaper->escapeHtml(__('Download PDF')) ?></span>
    </a>
</div>

<div class="order-details-items ordered">
    <div class="-mx-4">
        <ul class="items order-links">
            <li class="nav item current"><strong><?= $escaper->escapeHtml(__('Items Invoiced')) ?></strong></li>
        </ul>
    </div>
    <div class="p4 card">
        <div class="table-wrapper order-items overflow-auto">
            <table id="my-orders-table" class="w-full">
                <caption class="order-title sr-only"><?= __('Items Invoiced') ?></caption>
                <thead>
                    <tr>
                        <th class="col name p-2 text-left"><?= $escaper->escapeHtml(__('Product Name')) ?></th>
                        <th class="col sku p-2 text-left"><?= $escaper->escapeHtml(__('SKU')) ?></th>
                        <th class="col price p-2 text-left"><?= $escaper->escapeHtml(__('Price')) ?></th>
                        <th class="col qty p-2 text-left"><?= $escaper->escapeHtml(__('Qty')) ?></th>
                        <th class="col subtotal p-2 text-left"><?= $escaper->escapeHtml(__('Subtotal')) ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($invoiceLines as $invoiceLine): ?>
                    <?php
                    $itemNo = '';
                    if ((int)$invoiceLine["Type"] === 2) {
                    $itemNo = $invoiceLine["No."];}
                    ?>
                    <?php if ($invoiceLine["Type"] < 1): ?>
                    <tr class="even:bg-gray-100 align-top">
                        <td class="col name p-2" data-th="Product Name">
                            <strong class="product name product-item-name">
                                <?= $escaper->escapeHtml($invoiceLine["Description"]) ?>
                            </strong>
                        </td>
                        <td class="col sku p-2" data-th="SKU"></td>
                        <td class="col price p-2" data-th="Price">
                        </td>
                        <td class="col qty p-2" data-th="Qty">
                        </td>
                        <td class="col subtotal p-2" data-th="Subtotal">
                        </td>
                    </tr>
                    <?php else: ?>
                    <?php $qty = (float)$invoiceLine["Quantity"];
                    if ($qty == 0) {$qty = 1;}
                    ?>
                    <tr class="even:bg-gray-100 align-top">
                        <td class="col name p-2" data-th="Product Name">
                            <strong class="product name product-item-name">
                                <?= $escaper->escapeHtml($invoiceLine["Description"]) ?>
                            </strong>
                        </td>
                        <td class="col sku p-2" data-th="SKU"><?= $escaper->escapeHtml($itemNo) ?></td>
                        <td class="col price p-2" data-th="Price">
                            <span class="price-excluding-tax" data-label="Excl. Tax">
                                <span class="cart-price">
                                    <span class="price">
                                        <?= $escaper->escapeHtml($invoice["Currency Code"]) . ' ' .
                                        number_format((float)$invoiceLine["Amount"] / $qty, 2, ',', '.') ?>
                                    </span>
                                </span>
                            </span>
                        </td>
                        <td class="col qty" data-th="Qty">
                            <ul class="items-qty">
                                <li class="item">
                                    <span class="content">
                                        <?= $escaper->escapeHtml($invoiceLine["Quantity"]) ?>
                                    </span>
                                </li>
                            </ul>
                        </td>
                        <td class="col subtotal" data-th="Subtotal">
                            <span class="price-excluding-tax" data-label="Excl. Tax">
                                <span class="cart-price">
                                    <span class="price">
                                        <?= $escaper->escapeHtml($invoice["Currency Code"]) . ' ' .
                                        number_format((float)$invoiceLine["Line Amount"], 2, ',', '.') ?>
                                    </span>
                                </span>
                            </span>
                        </td>
                    </tr>
                    <?php endif; ?>
                    <?php endforeach; ?>
                </tbody>

                <tfoot>
                    <tr class="subtotal">
                        <th colspan="4" class="p-2 text-right" scope="row">
                            <?= $escaper->escapeHtml(__('Subtotal')) ?>
                        </th>
                        <td class="amount" data-th="Subtotal">
                            <span class="price">
                                <?= $escaper->escapeHtml($invoice["Currency Code"]); ?>
                                <?= $escaper->escapeHtml(number_format((float)$invoice["Amount"], 2, ',', '.')) ?>
                            </span>
                        </td>
                    </tr>
                    <tr class="shipping">
                        <th colspan="4" class="p-2 text-right" scope="row">
                            <?= $escaper->escapeHtml(__('VAT')) ?>
                        </th>
                        <td class="amount" data-th="VAT &amp; VAT">
                            <span class="price"><?= $escaper->escapeHtml($invoice["Currency Code"]); ?>
                                <?= $escaper->escapeHtml(number_format((float)$invoice["Amount Including VAT"] - (float)$invoice["Amount"], 2, ',', '.')) ?>
                            </span>
                        </td>
                    </tr>
                    <tr class="grand_total">
                        <th colspan="4" class="p-2 text-right" scope="row">
                            <strong><?= $escaper->escapeHtml(__('Grand Total')) ?></strong>
                        </th>
                        <td class="amount" data-th="Grand Total">
                            <strong>
                                <span class="price"><?= $escaper->escapeHtml($invoice["Currency Code"]); ?>
                                    <?= $escaper->escapeHtml(number_format((float)$invoice["Amount Including VAT"], 2, ',', '.')) ?>
                                </span>
                            </strong>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
        <div class="actions-toolbar">
            <div class="secondary">
                <a class="action back" href="/invoices/invoicelist/">
                    <span><?= $escaper->escapeHtml(__('Back to My Invoices')) ?></span>
                </a>
            </div>
        </div>
    </div>
</div>

<div class="mt-8">
    <div class="block-title mb-2">
        <strong><?= $escaper->escapeHtml(__('Invoice Information')) ?></strong>
    </div>
    <div class="p-4 card">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div class="order-shipping-address">
                <strong class="block text-lg mb-2">
                    <?= $escaper->escapeHtml(__('Shipping Address')) ?>
                </strong>
                <address class="not-italic">
                    <?= $escaper->escapeHtml($invoice["Ship-to Name"]); ?><br />
                    <?= $escaper->escapeHtml($invoice["Ship-to Address"]); ?><br />
                    <?= $escaper->escapeHtml($invoice["Ship-to City"]); ?>,
                    <?= $escaper->escapeHtml($invoice["Ship-to Post Code"]); ?><br />
                    <?= $escaper->escapeHtml($invoice["Ship-to Country/Region Code"]); ?><br />
                </address>
            </div>
            <div class="order-shipping-method">
                <strong class="block text-lg mb-2">
                    <?= $escaper->escapeHtml(__('Shipping Method')) ?>
                </strong>
                <div><?= $escaper->escapeHtml($invoice["Shipment Method Code"]); ?></div>
            </div>
            <div class="order-billing-address">
                <strong class="block text-lg mb-2">
                    <?= $escaper->escapeHtml(__('Billing Address')) ?>
                </strong>
                <address class="not-italic">
                    <?= $escaper->escapeHtml($invoice["Bill-to Name"]); ?><br />
                    <?= $escaper->escapeHtml($invoice["Bill-to Address"]); ?><br />
                    <?= $escaper->escapeHtml($invoice["Bill-to City"]); ?>,
                    <?= $escaper->escapeHtml($invoice["Bill-to Post Code"]); ?><br />
                    <?= $escaper->escapeHtml($invoice["Bill-to Country/Region Code"]); ?><br />
                </address>
            </div>
            <div class="order-billing-method">
                <strong class="block text-lg mb-2">
                    <?= $escaper->escapeHtml(__('Payment Method')) ?>
                </strong>
                <dl class="payment-method checkmemo">
                    <?= $escaper->escapeHtml($invoice["Payment Method Code"]); ?>
                </dl>
            </div>
        </div>
    </div>
</div>
