<?php declare(strict_types=1);

use Commerce365\Invoices\Block\InvoiceList;
use Magento\Framework\Escaper;

/** @var InvoiceList $block */
/** @var Escaper $escaper */

$totalResults = 0;
$invoices = [];
$invoicesResponse = $block->getInvoices();

if (!empty($invoicesResponse)) {
    $invoices = $invoicesResponse["salesDocuments"];
    $totalResults = $invoicesResponse["totalResults"];
}
?>

<div class="orders-history">
    <div class="text-2xl mb-6"><?= $escaper->escapeHtml(__('My Invoices')) ?></div>
    <?php if (count($invoices) > 0): ?>
    <form action="<?= $escaper->escapeUrl($block->getFilterActionUrl()) ?>" method="get">
        <div class="search-form-fields mb-4">
            <input type="text" class="form-input w-full md:w-96"
                placeholder="<?= $escaper->escapeHtml(__('Search...')) ?>" name="searchString" />
            <button type="submit" title="<?= $escaper->escapeHtml(__('Search')) ?>" class="btn btn-primary">
                <span><?= $escaper->escapeHtml(__('Search')) ?></span>
            </button>
        </div>
    </form>
    <?php if ($block->getSearchString()): ?>
    <?= $escaper->escapeHtml(__('Current filter')) ?>: <?= $escaper->escapeHtml($block->getSearchString()) ?>
    <a href="<?= $escaper->escapeUrl($block->getFilterActionUrl()) ?>"><?= $escaper->escapeHtml(__('Reset')) ?></a>
    <?php endif; ?>
    <div class="card mb-6 overflow-x-auto">
        <table id="my-orders-table" class="w-full">
            <thead>
                <tr>
                    <?php if($this->isColumnExists($invoices, 'No.')): ?>
                    <th scope="col" class="col id p-2 text-left">
                        <a href="<?= $block->getSortLink('No.')?>">
                            <?= __('Invoice #') ?>
                            <?= $block->getSortIcon('No.') ?>
                        </a>
                    </th>
                    <?php endif; ?>
                    <?php if($this->isColumnExists($invoices, 'Document Date')): ?>
                    <th scope="col" class="col date p-2 text-left">
                        <a href="<?= $block->getSortLink('Document Date')?>">
                            <?= __('Date') ?>
                            <?= $block->getSortIcon('Document Date') ?>
                        </a>
                    </th>
                    <?php endif; ?>
                    <?php if($this->isColumnExists($invoices, 'Order No.')): ?>
                        <th scope="col" class="col status p-2 text-left">
                            <a href="<?= $block->getSortLink('Order No.')?>">
                                <?= __('From Order #') ?>
                                <?= $block->getSortIcon('Order No.') ?>
                            </a>
                        </th>
                    <?php endif; ?>
                    <?php if($this->isColumnExists($invoices, 'Ship-to Name')): ?>
                    <th scope="col" class="col shipping p-2 text-left">
                        <a href="<?= $block->getSortLink('Ship-to Name')?>">
                            <?= __('Bill To') ?>
                            <?= $block->getSortIcon('Ship-to Name') ?>
                        </a>
                    </th>
                    <?php endif; ?>
                    <?php if($this->isColumnExists($invoices, 'Amount Including VAT')): ?>
                    <th scope="col" class="col total p-2 text-left">
                        <a href="<?= $block->getSortLink('Amount Including VAT')?>">
                            <?= __('Invoice Total') ?>
                            <?= $block->getSortIcon('Amount Including VAT') ?>
                        </a>
                    </th>
                    <?php endif; ?>
                    <?php if($this->isColumnExists($invoices, 'Remaining Amount')): ?>
                    <th scope="col" class="col total p-2 text-left">
                        <a href="<?= $block->getSortLink('Remaining Amount')?>">
                            <?= __('Open Amount') ?>
                            <?= $block->getSortIcon('Remaining Amount') ?>
                        </a>
                    </th>
                    <?php endif; ?>
                    <th scope="col" class="col id p-2 text-left"></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($invoices as $invoice): ?>
                <tr class="even:bg-gray-100">
                    <?php if($this->isColumnExists($invoices, 'No.')): ?>
                        <td data-th="Order #" class="col id"><?= $invoice["No."] ?></td>
                    <?php endif; ?>
                    <?php if($this->isColumnExists($invoices, 'Document Date')): ?>
                        <td data-th="Date" class="col date"><?= date_format(date_create($invoice["Document Date"]), "d-m-Y") ?></td>
                    <?php endif; ?>
                    <?php if($this->isColumnExists($invoices, 'Order No.')): ?>
                        <td data-th="Status #" class="col id"><?= $invoice["Order No."] ?></td>
                    <?php endif; ?>
                    <?php if($this->isColumnExists($invoices, 'Ship-to Name')): ?>
                    <td data-th="Ship To #" class="col id"><?= $invoice["Ship-to Name"] ?></td>
                    <?php endif; ?>
                    <?php if($this->isColumnExists($invoices, 'Amount Including VAT')): ?>
                    <td data-th="Total" class="col total"><?= $invoice["Currency Code"] ?>
                        <?= number_format((float)$invoice["Amount Including VAT"], 2, ',', '.') ?></td>
                    <?php endif; ?>
                    <?php if($this->isColumnExists($invoices, 'Remaining Amount')): ?>
                    <td data-th="Total" class="col total p-2"><?= $invoice["Currency Code"] ?>
                        <?= number_format((float)$invoice["Remaining Amount"], 2, ',', '.') ?></td>
                    <?php endif; ?>
                    <td data-th="Actions" class="col actions">
                        <a href="<?= $block->getViewUrl($invoice["id"]) ?>" class="action view">
                            <span><?=__("View Invoice") ?></span>
                        </a>
                        <span class="text-secondary-lighter"> | </span>
                        <a href="<?= $invoice["PDFUrl"] ?>" class="action order" target="_blank">
                            <span>PDF</span>
                        </a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php else: ?>
<div class="message info empty"><span><?= $escaper->escapeHtml(__('No Invoices found.')) ?></span></div>
<?php endif; ?>
</div>

<?php if ($totalResults > $block->getPageSize()): ?>
<div class="flex flex-col gap-2 md:flex-row md:items-center">
    <?php
            $totalPages = $invoicesResponse["totalPages"];
            $currentPage = $block->getPage();
        ?>
    <div>
        <?= $escaper->escapeHtml(__('Page: %1 of %2', $currentPage, $totalPages)) ?>
    </div>
    <div class="flex flex-wrap justify-between items-center gap-2">
        <?php if ($block->getPage() > 1): ?>
        <a href="<?= $block->getPreviousPageUrl() ?>" class="btn btn-secondary""><?= $escaper->escapeHtml(__('Previous')) ?></a>
            <?php endif; ?>
            <?php if ($block->getPage() > 1 && $block->getPage() < $invoicesResponse["totalPages"]): ?>
                -
            <?php endif; ?>
            <?php if ($block->getPage() < $invoicesResponse["totalPages"]): ?>
            <a href="<?= $block->getNextPageUrl() ?>"
            class="btn btn-secondary"><?= $escaper->escapeHtml(__('Next')) ?></a>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>
